### ISSUE TITLE
Balance on Date and Edit transaction (Not an Issue)

### ISSUE THREAD

**Issue by jacksumit** [yii2tech/balance#12]
Does this plugin allows to
1. Get Balance on a given date?
2. Edit a transaction? If yes will it update the balances on records created after this date?

**Comment by klimov-paul** [comment]
> Get Balance on a given date?

No.

> Edit a transaction? If yes will it update the balances on records created after this date?

No.

**Comment by klimov-paul** [comment]
However, you may achieve both goals using the queries depending on particular storage used.
