### ISSUE TITLE
Balance modifying

### ISSUE THREAD

**Issue by zhukovsergei** [yii2tech/balance#14]
Hello!
I have created a tables from tests:
_BalanceAccount_
![image](https://user-images.githubusercontent.com/1946769/35724944-142d5126-0832-11e8-86e2-ae135a9d37fc.png)

and _BalanceTransaction_
![image](https://user-images.githubusercontent.com/1946769/35724985-328e21c2-0832-11e8-83ac-eb193783c300.png)

In _BalanceAccount_ a balance column increase only with   
```
    $manager->accountBalanceAttribute = 'balance';
```

And transactions 
```
 $manager->transfer(1,2,100);
 $manager->increase(1, 500);
```
As i right understand, the balance column (20 in one case) should be equal of transactions sum (10+10).
So therefore, without this "accountBalanceAttribute" this is everything no make sense, because transaction doesn't modify the balance column ( _BalanceAccount_ table)

**Comment by klimov-paul** [comment]
I can not understand what are you asking about.
Manipulations over `ManagerDb::$accountBalanceAttribute` are covered by unit tests:
https://github.com/yii2tech/balance/blob/master/tests/ManagerDbTest.php#L93-L113

**Comment by zhukovsergei** [comment]
I meant without "accountBalanceAttribute" it's no make sense. With empty this attribute, account balance doesn't increase. Many transactions. Balance on account is 0. Is it correct?
If we will divide accountBalanceAttribute "balance1" and "balance2" it no make sense, because our transactions is monolith. We don't know which transaction impact on balance1 or balance2. Is it alright?

**Comment by klimov-paul** [comment]
Sorry, but I can not make any sense from what you are saying.
If there is a particular problem - write the unit test, which will expose it.
