### ISSUE TITLE
Account name not specified

### ISSUE THREAD

**Issue by dbd5** [yii2tech/balance#8]
Hi @klimov-paul ,

When an account is created on the fly, the account name is left blank. Your design provides every information needed to name the account when it is generated (for example, $userId . $accountType).
Did you make a decision not to name the account or is my configuration wrong somehow?

Thanks

**Comment by klimov-paul** [comment]
Account name is not necessary: such atribute is not used anywhere at this extension.

You may use `ManagerActiveRecord` and automatically generate name for the account at `ActiveRecord::afterSave()`, if you need it.
