### ISSUE TITLE
Transaction date not properly formated

### ISSUE THREAD

**Issue by dbd5** [yii2tech/balance#9]
Hi @klimov-paul ,

In the config I had specified date attribute and datevalue expression as follows
            // 'dateAttribute' => 'date',
            // 'dateAttributeValue' => "date('Y-m-d H:i:s',time())",

But the date entries made in the transaction table is "0000-00-00 00:00:00", just to be sure the issue is not from the date expression, I commented out both attributes from the config so I can pass the date attributeValue as part of extra data in the transaction array

```
            // extra data associated with transaction :
                [
                    'date'=> date("Y-m-d H:i:s", $payment->date),
                ]
```

Could you take a look and advise why the transaction date entries are not showing up in the proper mysql TIMESTAMP format?

Thanks again!

**Comment by klimov-paul** [comment]
``` php
'dateAttributeValue' => function() {
    return date("Y-m-d H:i:s");
}
```

**Comment by dbd5** [comment]
Thanks @klimov-paul ,

```
        // extra data associated with transaction :
            [
                'date'=> date("Y-m-d H:i:s", $payment->date),
            ]I actually prefer to pass it as part of the array of extra data associated with the transaction, 
```

it seems it is being overwritten by the extension code. Please advise how I can achieve this.

Regards
